#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


exec-once = [workspace 3; float; move 801 97; size 1025 500] kitty -e --hold fastfetch -c groups
exec-once = [workspace 3; float; move 1598 700; size 645 535] kitty -e --hold fastfetch -c hypr
exec-once = [workspace 3; float; move 340 600; size 1255 780] kitty -e --hold fastfetch -c full-info
#exec-once = [workspace 1; silent] spotify
#exec-once = [workspace 1; silent] discord
exec-once = waybar & waypaper --restore
