################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=desc:Dell Inc. S2719DGF 9K1N7P2,2560x1440@143.91Hz,0x0,1
monitor=desc:LG Electronics LG ULTRAGEAR 0x00002854,2560x1440@144,-1920x400,1


