################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=desc:Dell Inc. S2719DGF 9K1N7P2,2560x1440@143.91Hz,0x0,1
monitor=desc:LG Electronics LG ULTRAGEAR 0x00002854,2560x1440@144,-1920x400,1

workspace = 1, monitor:DP-1, persistent:true, default:true
workspace = 2, monitor:HDMI-A-1, persistent:true, default:true
workspace = special:game, name:Gaming, monitor:DP-1, persistent:true, decorate:false, rounding:false


windowrule = match:class steam, workspace 2 silent
windowrule = match:class net.lutris.Lutris, workspace 2 silent
windowrule = match:class spotify, workspace 2 silent
windowrule = match:class discord, workspace 2 silent
windowrule = match:class ^(?i)steam_app_.*, workspace special:game 
windowrule = match:class sober, workspace special:game 
