##############################
### WINDOWS AND WORKSPACES ###
##############################

# Persistent workspaces

workspace = 1, monitor:DP-1, persistent:true, default:true
workspace = 2, monitor:HDMI-A-1, persistent:true, default:true
workspace = special:game, name:Gaming, monitor:DP-1, persistent:true, decorate:false, rounding:false

# Move certain applications to specific workspaces

windowrule = match:class steam, workspace 2 silent
windowrule = match:class net.lutris.Lutris, workspace 2 silent
windowrule = match:class spotify, workspace 2 silent
windowrule = match:class discord, workspace 2 silent
windowrule = match:class ^(?i)steam_app_.*, workspace special:game 
windowrule = match:class sober, workspace special:game 

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 19 monitor_h-120
    float = yes
}
